name: Create Release with ZIP

on:
  push:
    tags:
      - 'v*.*.*'  # Ce déclencheur s'exécute sur un tag qui suit un format v1.0.0 par exemple
  workflow_dispatch:

jobs:
  create-zip:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up ZIP file
      run: mkdir -p output

    - name: Add files and folders to ZIP
      run: zip -r output/game.zip assets src requirements.txt run.py

    - name: Upload ZIP file as an artifact
      uses: actions/upload-artifact@v3
      with:
        name: game
        path: output/game.zip

  create-release:
    needs: create-zip
    runs-on: ubuntu-latest
    steps:
    - name: Download Artifact
      uses: actions/download-artifact@v3
      with:
        name: game
        path: ./output

    - name: Create GitHub Release
      id: create_release
      uses: actions/create-release@v1
      with:
        tag_name: ${{ github.ref }}  # Utilisez le tag de la branche courante
        release_name: Release ${{ github.ref }}
        body: "Release of Baton Bagarre"
        draft: false
        prerelease: false
        generate_release_notes: true

    - name: Upload ZIP to Release
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./output/game.zip
        asset_name: game.zip
        asset_content_type: application/zip
